[theme]
base="dark"
primaryColor="#3498DB"  # Azul vibrante e elegante
backgroundColor="#101216"  # Fundo levemente azul escuro
secondaryBackgroundColor="#22303C"  # Fundo secundário em cinza-azulado
textColor="#F5F5F5"  # Branco puro para máximo contraste
font="sans serif"
